version: "3"

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: changelog
    expose:
      - "5432"
    image: postgres:9.6
    logging: &logging
      driver: syslog
      options:
        syslog-address: "tcp+tls://logs7.papertrailapp.com:40471"
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    command: mix do ecto.create, ecto.migrate, phx.server
    environment:
      DB_URL: "ecto://postgres@db:5432/changelog"
      VIRTUAL_HOST: &vhost 2019.changelog.com
      HOST: *vhost
      STATIC_HOST: *vhost
      CM_API_TOKEN: /run/secrets/CM_API_TOKEN
      GITHUB_API_TOKEN: /run/secrets/GITHUB_API_TOKEN
      GITHUB_CLIENT_ID: /run/secrets/GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: /run/secrets/GITHUB_CLIENT_SECRET
      AWS_ACCESS_KEY_ID: /run/secrets/AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: /run/secrets/AWS_SECRET_ACCESS_KEY
      TWITTER_CONSUMER_KEY: /run/secrets/TWITTER_CONSUMER_KEY
      TWITTER_CONSUMER_SECRET: /run/secrets/TWITTER_CONSUMER_SECRET
      SECRET_KEY_BASE: /run/secrets/SECRET_KEY_BASE
      SIGNING_SALT: /run/secrets/SIGNING_SALT
      SLACK_INVITE_API_TOKEN: /run/secrets/SLACK_INVITE_API_TOKEN
      SLACK_APP_API_TOKEN: /run/secrets/SLACK_APP_API_TOKEN
      ROLLBAR_ACCESS_TOKEN: /run/secrets/ROLLBAR_ACCESS_TOKEN
      BUFFER_TOKEN: /run/secrets/BUFFER_TOKEN
      COVERALLS_REPO_TOKEN: /run/secrets/COVERALLS_REPO_TOKEN
      ALGOLIA_APPLICATION_ID: /run/secrets/ALGOLIA_APPLICATION_ID
      ALGOLIA_API_KEY: /run/secrets/ALGOLIA_API_KEY
    depends_on:
      - db
    image: thechangelog.com/changelog.com
    logging: *logging
    secrets:
      - campaign_monitor_api_token
      - github_api_token
      - github_client_id
      - github_client_secret
      - aws_access_key_id
      - aws_secret_access_key
      - twitter_consumer_key
      - twitter_consumer_secret
      - secret_key_base
      - signing_salt
      - slack_app_api_token
      - rollbar_access_token
      - buffer_token
      - coveralls_repo_token
      - algolia_application_id
      - algolia_api_key
    volumes:
      - uploads:./priv/uploads
  proxy:
    image: thechangelog/proxy
    logging: *logging
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/changelog.conf:/etc/nginx/conf.d/changelog.conf:ro
      - uploads:/var/www/uploads:ro

volumes:
  postgres:
  uploads:
