version: "3.6"

services:
  log:
    command: syslog+tls://logs7.papertrailapp.com:40471
    deploy:
      mode: global
      restart_policy:
        condition: any
    environment:
      SYSLOG_HOSTNAME: &host 2019.changelog.com
    image: gliderlabs/logspout:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      POSTGRES_USER: &pg_user changelog
      POSTGRES_DB: *pg_user
      # https://www.postgresql.org/docs/9.6/libpq-envars.html
      PGUSER: *pg_user
      PGDATABASE: *pg_user
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 5s
    image: postgres:9.6.11
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    command: mix do ecto.migrate, phx.server
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      DB_URL: "ecto://changelog@db:5432/changelog"
      PORT: 4000
      URL_HOST: *host
      URL_PORT: 80
      URL_SCHEME: http
      URL_STATIC_HOST: *host
      VIRTUAL_HOST: *host
    secrets:
      - CM_API_TOKEN
      - CM_SMTP_TOKEN
      - GITHUB_API_TOKEN
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - SECRET_KEY_BASE
      - SIGNING_SALT
      - SLACK_INVITE_API_TOKEN
      - SLACK_APP_API_TOKEN
      - ROLLBAR_ACCESS_TOKEN
      - BUFFER_TOKEN
      - COVERALLS_REPO_TOKEN
      - ALGOLIA_APPLICATION_ID
      - ALGOLIA_API_KEY
    depends_on:
      - db
    image: thechangelog/changelog.com
    ports:
      - "4000:4000"
    volumes:
      - uploads:/uploads
  proxy:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    image: thechangelog/proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - uploads:/var/www/uploads:ro

volumes:
  postgres:
  uploads:

secrets:
  CM_API_TOKEN:
    external: true
  CM_SMTP_TOKEN:
    external: true
  GITHUB_API_TOKEN:
    external: true
  GITHUB_CLIENT_ID:
    external: true
  GITHUB_CLIENT_SECRET:
    external: true
  AWS_ACCESS_KEY_ID:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
  TWITTER_CONSUMER_KEY:
    external: true
  TWITTER_CONSUMER_SECRET:
    external: true
  SECRET_KEY_BASE:
    external: true
  SIGNING_SALT:
    external: true
  SLACK_INVITE_API_TOKEN:
    external: true
  SLACK_APP_API_TOKEN:
    external: true
  ROLLBAR_ACCESS_TOKEN:
    external: true
  BUFFER_TOKEN:
    external: true
  COVERALLS_REPO_TOKEN:
    external: true
  ALGOLIA_APPLICATION_ID:
    external: true
  ALGOLIA_API_KEY:
    external: true
